messages:
  wrongSender: "This command can use only players!"
  wrongCommandArguments: "&l&6Команда введена неправильно!"
  pointNotExists: "&l&6Такого спавна нет!"
  prisonerHasNotOverdueSalary: "&l&6У вас нет просроченной зарплаты!"
  notEnoughSlots: "&l&6У вас недостаточно места в карманах, чтобы получить зарплату! Очистите карманы и напишите /getsalary"
  getOverdueSalary: "&l&6Вы получили просроченную зарплату!"
  leaveJob: "&l&6Вы уволились ПСЖ!"
  joinJob: "&l&6Вы устроились на работу!"
  notEnoughLevel: "&6&lУ вас недостаточный уровень, чтобы устроиться на эту работу!"
  selectionNotExists: "&l&cНужно выделить территорию!"
  newMiner: "&l&6Новая шахта под названием %name% создана!"
  minerIsAlreadyExists: "&l&6Шахта с таким именем уже существует!"
  minerNotExists: "&l&6Шахты с таким именем не существует!"
  pos1Add: "&l&6Вы установили первую точку!"
  pos2Add: "&l&6Вы установили вторую точку!"
  timeSet: "&l&6Вы установили время!"
  pointSet: "&l&6Вы установили точку спавна!"
  blocksSet: "&l&6Блоки шахты установлены!"
  minerDeleted: "&l&6Шахта была удалена!"
  prSumMustBe100: "&l&cНеправильные данные: общая сумма должна быть 100%"
  mineReloadSoon: "&l&6Шахта %name% скоро обновится!"
  mineReload: "&l&6Шахта %name% обновилась!"
cleanerPointCount: 0
cleaners:
chests:
jobLevels:
  miner: 2
  cleaner: 1
  cook: 3
cleaner:
  garbageBreak: 2
  garbagePickup: 1
  garbageAway: 2
  garbageCountPerCleaner: 10
  garbageSpawnIntensity: 10