messages:
  wrongSender: "This command can use only players!"
  wrongCommandArguments: "&l&6Команда введена неправильно!"
  pointNotExists: "&l&6Такого спавна нет!"
  prisonerHasNotOverdueSalary: "&l&6У вас нет просроченной зарплаты!"
  notEnoughSlots: "&l&6У вас недостаточно места в карманах, чтобы получить зарплату! Очистите карманы и напишите /getsalary"
  getOverdueSalary: "&l&6Вы получили просроченную зарплату!"
  leaveJob: "&l&6Вы уволились ПСЖ!"
  joinJob: "&l&6Вы устроились на работу!"
  notEnoughLevel: "&6&lУ вас недостаточный уровень, чтобы устроиться на эту работу!"
  selectionNotExists: "&l&cНужно выделить территорию!"
  newMiner: "&l&6Новая шахта под названием %name% создана!"
cleanerPointCount: 0
cleaners:
chests:
jobLevels:
  miner: 2
  cleaner: 1
  cook: 3
cleaner:
  garbageBreak: 2
  garbagePickup: 1
  garbageAway: 2
  garbageCountPerCleaner: 10
  garbageSpawnIntensity: 10