name: PLJobs
main: ru.prisonlife.pljobs.Main
version: v1.0
depend: [PLCore]
api-version: 1.13
description: Plugin for works
author: rntsdkv
commands:
  gowork:
    description: Manage with works
    permission: pljobs.gowork
    usage: /gowork <cleaner, miner, cook> or /gowork
  cleanersetpoint:
    description: Set new garbage spawn point
    permission: pljobs.cleaner.setpoint
    usage: /cleanersetpoin
  cleanerdelpoint:
    description: Delete garbage spawn point
    permission: pljobs.cleaner.delpoint
    usage: /cleanerdelpoint <id>
  cleanerlist:
    description: List of areas
    permission: pljobs.cleaner.list
    usage: /cleanerlist
  setgarbage:
    description: Click on chest to set garbage!
    permission: pljobs.cleaner.setgarbage
    usage: /setgarbage
  getsalary:
    description: Get your overdue salary if you kicked from server
    permission: pljobs.getsalary
    usage: /getsalary